/*-------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation.  All rights reserved.
 *
 * documentdb_tests/tests/connection_limit_tests.rs
 *
 *-------------------------------------------------------------------------
 */

/// Integration tests for the `max_incoming_connections` gateway configuration option.
///
/// The gateway uses a semaphore to cap concurrent TCP connections. When the
/// limit is reached, new connections are accepted at the OS level but
/// immediately dropped, causing the `MongoDB` driver to report a server
/// selection timeout.
///
/// This test verifies the full lifecycle in four phases:
///
/// 1. Open `MAX_CLIENTS` clients and confirm every one connects.
/// 2. Attempt `OVERFLOW_BATCH` more connections and confirm they are all rejected.
/// 3. Drop `OVERFLOW_BATCH` existing clients and wait for the server to
///    reclaim the freed permits.
/// 4. Reconnect `OVERFLOW_BATCH` new clients into the freed slots and confirm
///    they succeed.
///
/// Constants:
/// - `PORT` — the gateway listen port (matches the default used by all tests).
/// - `MAX_CONNECTIONS` — the connection cap passed to the gateway config.
/// - `MAX_CLIENTS` — the number of clients we can open (`MAX_CONNECTIONS / 2`),
///   because the `MongoDB` driver opens 2 TCP connections per client (one for
///   the application pool and one for SDAM monitoring).
/// - `OVERFLOW_BATCH` — how many extra clients to try, drop, and reconnect
///   in each phase. Defined as `MAX_CLIENTS / 10` so it scales automatically.
///
/// Note: this test is self-contained rather than delegating to a `commands::`
/// module because it tests gateway infrastructure, not `MongoDB` commands.
use std::time::Duration;

use bson::doc;
use documentdb_gateway_core::configuration::{
    CertInputType, CertificateOptions, DocumentDBSetupConfiguration,
};
use documentdb_tests::test_setup::{
    clients::{self, TEST_PASSWORD, TEST_USERNAME},
    initialize,
};
use mongodb::{
    error::{Error, ErrorKind},
    Client,
};

const PORT: u16 = 10260;
const MAX_CONNECTIONS: usize = 1000;
/// The `MongoDB` driver opens 2 TCP connections per client (one application
/// connection and one SDAM monitor connection), so the number of clients
/// we can open is half the connection limit.
const MAX_CLIENTS: usize = MAX_CONNECTIONS / 2;
const OVERFLOW_BATCH: usize = MAX_CLIENTS / 10;

/// Helper: returns a gateway configuration with a cap on incoming connections.
fn gateway_config() -> DocumentDBSetupConfiguration {
    let system_user = std::env::var("PostgresSystemUser").unwrap_or(whoami::username());

    DocumentDBSetupConfiguration {
        node_host_name: "localhost".to_owned(),
        blocked_role_prefixes: Vec::new(),
        gateway_listen_port: Some(PORT),
        allow_transaction_snapshot: Some(false),
        certificate_options: CertificateOptions {
            cert_type: CertInputType::PemAutoGenerated,
            ..Default::default()
        },
        postgres_system_user: system_user.clone(),
        postgres_data_user: system_user,
        max_incoming_connections: Some(MAX_CONNECTIONS),
        ..Default::default()
    }
}

/// Builds an authenticated, TLS-enabled `MongoDB` client pointed at the test gateway.
///
/// Calls `clients::test_client_options`, then applies two settings this test:
/// - `max_pool_size = 1`: each client opens a predictable number of TCP
///   connections, so the test can reason about the exact connection count.
/// - `server_selection_timeout = 500ms`: when the gateway refuses a connection,
///   the driver reports the error quickly instead of waiting the default 30
///   seconds. Kept short so the rejected-connection checks don't dominate
///   runtime.
fn create_client() -> Result<Client, Error> {
    let mut options = clients::test_client_options(TEST_USERNAME, TEST_PASSWORD)?;
    options.max_pool_size = Some(1);
    options.server_selection_timeout = Some(Duration::from_millis(500));

    Client::with_options(options)
}

/// Helper: sends a ping to force the client to open a TCP connection.
async fn ping(client: &Client) -> Result<(), Error> {
    client
        .database("admin")
        .run_command(doc! { "ping": 1 })
        .await?;
    Ok(())
}

/// Helper: asserts that a ping fails with a server selection timeout, which is what
/// the driver reports when the gateway drops the TCP stream.
fn assert_connection_rejected(result: Result<(), Error>, context: &str) {
    match result {
        Err(err) => assert!(
            matches!(*err.kind, ErrorKind::ServerSelection { .. }),
            "{context}: expected ServerSelection error, got: {err}"
        ),
        Ok(()) => panic!("{context}"),
    }
}

/// Verifies that the gateway enforces its maximum connection limit and
/// recovers gracefully when clients disconnect.
#[tokio::test]
async fn test_max_incoming_connections() -> Result<(), Error> {
    let _ = initialize::initialize_with_config(gateway_config())
        .await
        .expect("gateway should start");

    // Allow the discarded initialization client's connection to fully close
    // so its semaphore permit is released before we start counting slots.
    tokio::time::sleep(Duration::from_millis(500)).await;

    // ---- Phase 1: fill all connection slots ----
    // Clients are held in this vec to keep their TCP connections alive.
    #[expect(
        clippy::collection_is_never_read,
        reason = "clients are held to keep TCP connections alive"
    )]
    let mut active_clients = Vec::with_capacity(MAX_CLIENTS);
    for i in 0..MAX_CLIENTS {
        let client = create_client().expect("client creation should succeed");
        ping(&client)
            .await
            .unwrap_or_else(|e| panic!("connection {i} should succeed: {e}"));
        active_clients.push(client);
    }

    // ---- Phase 2: verify a batch of extra connections are all rejected ----
    for i in 0..OVERFLOW_BATCH {
        let client = create_client().expect("client creation should succeed");
        let result = ping(&client).await;
        assert_connection_rejected(
            result,
            &format!("overflow connection {i} should be rejected"),
        );
    }

    // ---- Phase 3: free up a batch of slots ----
    for _ in 0..OVERFLOW_BATCH {
        active_clients.pop();
    }

    // Permits are released asynchronously as the server detects each closed
    // connection, so we retry with back-off until a slot opens up.
    let mut recovered = false;
    for attempt in 0..20 {
        tokio::time::sleep(Duration::from_millis(100 * (attempt + 1))).await;
        let probe = create_client()?;
        if ping(&probe).await.is_ok() {
            active_clients.push(probe);
            recovered = true;
            break;
        }
    }
    assert!(recovered, "should reconnect after some clients disconnect");

    // ---- Phase 4: fill the remaining freed slots back up ----
    let remaining_slots = OVERFLOW_BATCH - 1; // one slot used by the recovery probe
    for i in 0..remaining_slots {
        let client = create_client().expect("client creation should succeed");
        ping(&client)
            .await
            .unwrap_or_else(|e| panic!("reconnection {i} should succeed: {e}"));
        active_clients.push(client);
    }

    Ok(())
}
