OSS_SRC_DIR = ../../

MODULE_big = pg_documentdb_extended_rum_core_builtin_rmgr
RUM_BUILT_IN_RMGR_MODE=yes
RUM_BUILD_ONLY_CORE_RMGR=yes
OBJDIR=$(OSS_SRC_DIR)pg_documentdb_extended_rum/core_builtin_rmgr
CORESRCDIR=$(OSS_SRC_DIR)pg_documentdb_extended_rum/core/src
COREINCDIR=$(OSS_SRC_DIR)pg_documentdb_extended_rum/core/include

EXTRA_CLEAN += $(OBJDIR)/src

include $(OSS_SRC_DIR)/pg_documentdb_extended_rum/core/Makefile
